### ISSUE TITLE
Broken signatures

### ISSUE THREAD

**Issue by Sparker95** [winseros/gulp-armapbo-plugin#6]
Hi!

I am signing a .pbo made by this tool. It seems like even though the .pbo is loaded in arma properly, and DSUtils shows no signature errors, arma fails to verify signatures somehow. To confirm, I have packed same folder with the default arma addon builder, then signed it, and it has no issues. Although it might be that I'm doing something wrong.

**Comment by winseros** [comment]
@Sparker95   Sorry for answering with such a huge delay, but I had notifications turned off and didn't see the issue.

To make the signatures recognized by the game, you need to provide an extension with the name `prefix` and value related to the particular pbo. e.g.

``` Javascript
pbo.pack({
            fileName: 'myaddon.pbo',
            extensions: [{
                name: 'prefix',
                value: 'myaddon'
            }]
        }
```

Otherwise, it really will not be recognized.

**Comment by Sparker95** [comment]
Hi, thank you for lettimg us know 👍
